name: Check Nix flake
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch: # allow manual trigger
jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v8
        with:
          fail-mode: true
          send-statistics: false
      - name: Check that test NixOS VM builds
        uses: extractions/setup-just@v2
        run: just build-vm
